### ISSUE TITLE
'func' is not exported by prop-types

### ISSUE THREAD

**Issue by exepirit** [mui-org/material-ui-pickers#1992]
## Current Behavior 😯

Build fails with error

```
97% (715): node_modules/css-vendor/node_modules/@babel/runtime/helpers/esm/arrayLikeToArray.js[!] Error: 'func' is not exported by node_modules
\prop-types\index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules\@material-ui\pickers\esm\useUtils-cfb96ac9.js (2:9)
1: import { createContext, useMemo, createElement, useContext } from 'react';
2: import { func, oneOfType, object, string, element, arrayOf } from 'prop-types';
            ^
3:
4: var MuiPickersContext = createContext(null);
Error: 'func' is not exported by node_modules\prop-types\index.js
    at error (node_modules\rollup\dist\rollup.js:5351:30)
    at Module.error (node_modules\rollup\dist\rollup.js:9650:9)
    at handleMissingExport (node_modules\rollup\dist\rollup.js:9567:21)
    at Module.traceVariable (node_modules\rollup\dist\rollup.js:9958:17)
    at ModuleScope.findVariable (node_modules\rollup\dist\rollup.js:8627:39)
    at MemberExpression.bind (node_modules\rollup\dist\rollup.js:7449:49)
    at Property$1.bind (node_modules\rollup\dist\rollup.js:3130:23)
    at Property$1.bind (node_modules\rollup\dist\rollup.js:8244:15)
    at ObjectExpression.bind (node_modules\rollup\dist\rollup.js:3126:31)
    at ObjectExpression.bind (node_modules\rollup\dist\rollup.js:7927:15)
```

## Steps to Reproduce 🕹

Steps:

1. `npm install @material-ui/pickers`
2. Add `DatePicker` into any React component
3. `npm build`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.9.10  |
| @material-ui/pickers | v3.2.9  |
| React       | v16.13.1 |
| npm        | v6.14.6 |

**Comment by oliviertassinari** [comment]
@exepirit Please provide a minimal reproduction test case with @material-ui/pickers@v4.0.0-alpha.9. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/material-ui-date-picker-ppt05) _may_ be a good starting point. Thank you!
