### ISSUE TITLE
[4.0.0-alpha-10] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by williamluke4** [mui-org/material-ui-pickers#2044]
- [x]  The issue is present in the latest release.
- [x]  I have searched the issues of this repository and believe that this is not a duplicate.

# Info
```json
{
   "@material-ui/core": "4.11.0",
    "@material-ui/icons": "4.9.1",
    "@material-ui/lab": "4.0.0-alpha.56",
    "@material-ui/pickers": "^4.0.0-alpha.10",
    "next": "^9.5.0",
}
```
# Logs
```
event - compiled successfully
@atto-byte/frontend: C:\Users\willi\Github\bush-and-beyond\node_modules\@material-ui\pickers\LocalizationProvider.js:1
@atto-byte/frontend: import 'react';
@atto-byte/frontend: ^^^^^^
@atto-byte/frontend: SyntaxError: Cannot use import statement outside a module
@atto-byte/frontend:     at wrapSafe (internal/modules/cjs/loader.js:1152:16)
@atto-byte/frontend:     at Module._compile (internal/modules/cjs/loader.js:1200:27)
@atto-byte/frontend:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
@atto-byte/frontend:     at Module.load (internal/modules/cjs/loader.js:1085:32)
@atto-byte/frontend:     at Function.Module._load (internal/modules/cjs/loader.js:950:14)
@atto-byte/frontend:     at Module.require (internal/modules/cjs/loader.js:1125:19)
@atto-byte/frontend:     at require (internal/modules/cjs/helpers.js:75:18)
@atto-byte/frontend:     at Object.@material-ui/pickers/LocalizationProvider (C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:1260:18)
@atto-byte/frontend:     at __webpack_require__ (C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:23:31)  
@atto-byte/frontend:     at Module../pages/_app.tsx (C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:644:99)
@atto-byte/frontend:     at __webpack_require__ (C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:23:31)  
@atto-byte/frontend:     at Object.0 (C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:1116:18)
@atto-byte/frontend:     at __webpack_require__ (C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:23:31)  
@atto-byte/frontend:     at C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:91:18
@atto-byte/frontend:     at Object.<anonymous> (C:\Users\willi\Github\bush-and-beyond\packages\frontend\.next\server\pages\_app.js:94:10)   
@atto-byte/frontend:     at Module._compile (internal/modules/cjs/loader.js:1236:30)
@atto-byte/frontend: event - build page: /next/dist/pages/_error
```

**Comment by williamluke4** [comment]
# Reproduction
1. https://codesandbox.io/s/material-ui-nextjs-z8x9l
1. Run `yarn dev`

**Comment by dmtrKovalenko** [comment]
The problem is with import `import { LocalizationProvider } from "@material-ui/pickers";` will work

https://codesandbox.io/s/material-ui-nextjs-x8120?file=/pages/_app.tsx:205-265
